[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ATMB"
authors = [{name = "Eve Epanchina", email = "epa.genia@gmail.com"}]
dynamic = ["version", "description"]
